name: Project Name
title: Baked with Awestruct
org: Organization
base_url: ''
profiles:
  production:
    base_url: http://Texasjake95.github.io/
    deploy:
      host: github_pages
      # use gh-branch for repositories other than <username>.github.io
      # use master branch for <username>.github.io repository
      branch: master